{ config, lib, pkgs, ... }:

let
  cfg = config.services.gnome-ms-sso-plugin;
  resolvconfBin = lib.getExe' pkgs.openresolv "resolvconf";
  resolvectlBin = lib.getExe' pkgs.systemd "resolvectl";
  grepBin = lib.getExe' pkgs.gnugrep "grep";
  awkBin = lib.getExe' pkgs.gawk "awk";
  cleanupScript = pkgs.writeShellScript "nm-ms-sso-cleanup" ''
    iface="''${VPN_IP_IFACE:-''${DEVICE_IFACE:-$1}}"
    event="$2"

    case "$event" in
      vpn-down|down)
        if [ -r /etc/resolv.conf ] && ${grepBin} -q '^# Generated by resolvconf' /etc/resolv.conf; then
          if [ -n "$iface" ]; then
            ${resolvconfBin} -d "$iface" || true
          fi
          ${resolvconfBin} -l | ${awkBin} '/^# resolv.conf from /{print $NF}' | ${grepBin} '^tun' | while read -r dev; do
            [ -n "$dev" ] && ${resolvconfBin} -d "$dev" || true
          done
          ${resolvconfBin} -u || true
        elif [ -n "$iface" ] && [ -x ${resolvectlBin} ]; then
          ${resolvectlBin} revert "$iface" || true
        fi
        ;;
    esac
  '';
in
{
  options.services.gnome-ms-sso-plugin = {
    enable = lib.mkEnableOption "GNOME MS SSO NetworkManager plugin";

    withOverlay = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Add the local overlay that provides networkmanager-ms-sso.";
    };

    autoKillStale = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Kill stale nm-ms-sso-service processes on NetworkManager restart.";
    };

    autoCleanupDns = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Clean up DNS entries on VPN disconnect.";
    };
  };

  config = {
    nixpkgs.overlays = lib.optionals cfg.withOverlay [
      (import ./overlay.nix)
    ];
  } // lib.mkIf cfg.enable {
    networking.networkmanager.plugins = lib.mkAfter [
      pkgs.networkmanager-ms-sso
    ];

    systemd.services.NetworkManager.serviceConfig.ExecStartPre =
      lib.optional cfg.autoKillStale
        "-${lib.getExe' pkgs.procps "pkill"} -KILL -f nm-ms-sso-service";

    networking.networkmanager.dispatcherScripts = lib.optional cfg.autoCleanupDns {
      source = cleanupScript;
      type = "basic";
    };

    systemd.tmpfiles.rules = pkgs.networkmanager-ms-sso.networkManagerTmpfilesRules or [ ];
  };
}
